document.addEventListener("DOMContentLoaded", () => {
    const canvas = document.getElementById("tree-canvas");
    const ctx = canvas.getContext("2d");

    const panel = document.getElementById("detail-panel");
    const closeBtn = document.getElementById("close-btn");
    const panelTitle = document.getElementById("panel-title");
    const panelContent = document.getElementById("panel-content");
    const riskVal = document.getElementById("risk-val");
    const panelBadge = document.getElementById("panel-badge");
    const resetZoomBtn = document.getElementById("reset-zoom-btn");

    let width, height;
    let hoveredNode = null;
    let activeNode = null;
    let selectedMainCategory = null; 
    let particles = [];
    let backgroundBranches = [];

    // KAMERA SİSTEMİ
    const camera = {
        x: 0,
        y: 0,
        zoom: 1,
        targetX: 0,
        targetY: 0,
        targetZoom: 1
    };

    let activeTypewriterTimer = null;

    function typeWriterEffect(element, text, speed = 15) {
        if (activeTypewriterTimer) {
            clearTimeout(activeTypewriterTimer);
            activeTypewriterTimer = null;
        }
        element.textContent = "";
        let i = 0;
        function type() {
            if (i < text.length) {
                element.textContent += text.charAt(i);
                i++;
                activeTypewriterTimer = setTimeout(type, speed);
            } else {
                activeTypewriterTimer = null;
            }
        }
        type();
    }

    function resize() {
        const dpr = window.devicePixelRatio || 1;
        width = canvas.parentElement.clientWidth;
        height = canvas.parentElement.clientHeight;
        canvas.width = width * dpr;
        canvas.height = height * dpr;
        ctx.scale(dpr, dpr);

        // MOBİL DİKEY EKRAN DENGESİ (RESPONSIVE CAMERA & SCALE)
        const isMobile = width < 768;
        const isPortrait = height > width;

        if (!selectedMainCategory) {
            if (isMobile && isPortrait) {
                // Mobilde ağacın ekrana tam sığması için kamerayı geriye çekip merkeze oturtuyoruz
                camera.targetZoom = 0.45;
                camera.zoom = 0.45;
                camera.targetY = -height * 0.35;
                camera.y = -height * 0.35;
                camera.targetX = 0;
                camera.x = 0;
            } else {
                camera.targetZoom = 1;
                camera.targetY = 0;
                camera.targetX = 0;
            }
        }

        generateBackgroundBranches();
    }

    window.addEventListener("resize", resize);
    window.addEventListener("orientationchange", () => {
        setTimeout(resize, 200);
    });

    // --- AĞAÇ VE VERİ HARİTASI ---
    function getNodes() {
        const cx = width / 2;
        const cy = height;

        // Mobil için dinamik genişlik katsayısı
        const isMobile = width < 768;
        const mainXOffset = isMobile ? width * 0.8 : width * 0.32;

        const mainNodes = [
            {
                id: "core",
                label: "LUCAIN [CORE]",
                type: "root",
                x: cx,
                y: cy - 110,
                radius: isMobile ? 42 : 36,
                color: "#00f0ff",
                parent: null,
                desc: "LUCAIN CHRONO CORE: The master database log where all temporal lines intersect. A hidden core protected under the 00-ALPHA protocol in the state archives."
            },
            {
                id: "past",
                label: "PAST INTERVENTIONS",
                type: "main",
                x: cx - mainXOffset,
                y: cy - height * 0.78,
                radius: isMobile ? 30 : 24,
                color: "#00f0ff",
                parent: "apex",
                desc: "PAST INTERVENTIONS: Break records and chronological jump analyses of past timelines by Lucain."
            },
            {
                id: "present",
                label: "PRESENT REALITY",
                type: "main",
                x: cx,
                y: cy - height * 0.82,
                radius: isMobile ? 32 : 26,
                color: "#00f0ff",
                parent: "apex",
                desc: "CURRENT REALITY: The current primary time matrix and quantum anchor state."
            },
            {
                id: "future",
                label: "FUTURE SIMULATION",
                type: "main",
                x: cx + mainXOffset,
                y: cy - height * 0.78,
                radius: isMobile ? 30 : 24,
                color: "#00f0ff",
                parent: "apex",
                desc: "FUTURE SIMULATIONS: Secondary time arms and collapse scenarios generated by the probability calculation engine."
            }
        ];

        let subNodes = [];

        if (selectedMainCategory) {
            const targetMain = mainNodes.find(m => m.id === selectedMainCategory);
            const baseX = targetMain ? targetMain.x : cx;
            const baseY = targetMain ? targetMain.y - 520 : cy - height; 

            if (selectedMainCategory === "past") {
                subNodes = [
                    { id: "p_root", label: "PAST DATA BUS", type: "usb_base", x: baseX, y: baseY + 200, radius: 18, color: "#00f0ff", desc: "HISTORY DATA PATH: 5W1H chronal analysis matrix." },
                    { id: "p_how", label: "HOW? [Time Excision]", type: "usb_node", shape: "arrow", x: baseX, y: baseY - 120, radius: 16, color: "#00f0ff", parent: "p_root", desc: "Method: Slicing and stealing precise temporal frames directly from the timeline continuum." },
                    { id: "p_who", label: "1K: WHO? [Lucain]", type: "usb_node", shape: "circle", branchOriginY: baseY + 120, x: baseX - 140, y: baseY + 50, radius: 14, color: "#00f0ff", parent: "p_root", desc: "Civil Identity: Lucain. His first archival record before he acquired his time abilities." },
                    { id: "p_when", label: "WHEN? [T-2024]", type: "usb_node", shape: "square", branchOriginY: baseY + 80, x: baseX + 140, y: baseY + 10, radius: 14, color: "#00f0ff", parent: "p_root", desc: "Time Zone: T-2024 relative timeline." },
                    { id: "p_what", label: "WHAT? [Jump #09]", type: "usb_node", shape: "square", branchOriginY: baseY + 20, x: baseX - 150, y: baseY - 40, radius: 14, color: "#00f0ff", parent: "p_root", desc: "Event: Micro-tear occurring in temporal tissue during Time Jump 9." },
                    { id: "p_where", label: "WHERE? [Sector-7]", type: "usb_node", shape: "circle", branchOriginY: baseY - 30, x: baseX + 150, y: baseY - 80, radius: 14, color: "#00f0ff", parent: "p_root", desc: "Location: Sector-7 Underground Laboratory." },
                    { id: "p_why", label: "WHY? [The Ugly Truth]", type: "usb_node", shape: "circle", branchOriginY: baseY - 60, x: baseX - 140, y: baseY - 100, radius: 14, color: "#00f0ff", parent: "p_root", desc: "Reason: To prevent a coronal reactor explosion." }
                ];
            } else if (selectedMainCategory === "present") {
                subNodes = [
                    { id: "pr_root", label: "PRESENT DATA BUS", type: "usb_base", x: baseX, y: baseY + 200, radius: 18, color: "#00f0ff", desc: "CURRENT DATA BUS." },
                    { id: "pr_anchor", label: "CHRONO ANCHOR", type: "usb_node", shape: "arrow", x: baseX, y: baseY - 80, radius: 14, color: "#00f0ff", parent: "pr_root", desc: "Anchor Frequency: A 440Hz quantum resonance that anchors reality." },
                    { id: "pr_sync", label: "CORE SYNC", type: "usb_node", shape: "square", x: baseX - 140, y: baseY + 20, radius: 14, color: "#00f0ff", parent: "pr_root", desc: "Synchronization: 100% overlap with the master log." }
                ];
            } else if (selectedMainCategory === "future") {
                subNodes = [
                    { id: "f_root", label: "FUTURE DATA BUS", type: "usb_base", x: baseX, y: baseY + 200, radius: 18, color: "#00f0ff", desc: "THE FUTURE OF SIMULATION." },
                    { id: "f_paradox", label: "PARADOX BREACH", type: "usb_node", shape: "square", isCorrupted: true, x: baseX, y: baseY - 80, radius: 16, color: "#ff0055", parent: "f_root", desc: "CRITICAL WARNING: The Grandfather Paradox is breaking!" },
                    { id: "f_collapse", label: "COLLAPSE SIM", type: "usb_node", shape: "circle", x: baseX - 150, y: baseY + 30, radius: 14, color: "#00f0ff", parent: "f_root", desc: "Risk of Collapse: Overlapping timelines." }
                ];
            }
        }

        return [...mainNodes, ...subNodes];
    }

    function generateBackgroundBranches() {
        backgroundBranches = [];
        const cx = width / 2;
        const cy = height;

        const isMobile = width < 768;
        const mainXOffset = isMobile ? width * 0.8 : width * 0.32;

        const mainOrigins = [
            { x: cx - mainXOffset, y: cy - height * 0.78 },
            { x: cx, y: cy - height * 0.82 },
            { x: cx + mainXOffset, y: cy - height * 0.78 }
        ];

        mainOrigins.forEach(origin => {
            for (let i = 0; i < 20; i++) {
                const angle = -Math.PI / 2 + (Math.random() - 0.5) * 2.5;
                const len = 150 + Math.random() * 380;
                const endX = origin.x + Math.cos(angle) * len;
                const endY = origin.y + Math.sin(angle) * len;
                
                backgroundBranches.push({
                    x1: origin.x, y1: origin.y,
                    x2: endX, y2: endY,
                    cpX: (origin.x + endX) / 2 + (Math.random() - 0.5) * 120,
                    cpY: (origin.y + endY) / 2 + (Math.random() - 0.5) * 120,
                    alpha: 0.08 + Math.random() * 0.28,
                    width: 0.4 + Math.random() * 1.6
                });
            }
        });
    }

    function initParticles() {
        particles = [];
        for (let i = 0; i < 35; i++) {
            particles.push({
                x: Math.random() * width,
                y: Math.random() * height,
                size: Math.random() * 2 + 0.5,
                vx: (Math.random() - 0.5) * 0.4,
                vy: -Math.random() * 0.5 - 0.2,
                alpha: Math.random() * 0.7 + 0.2
            });
        }
    }
    initParticles();
    resize();

    function drawTaperedBranch(p1, p2, startWidth, endWidth, color, glowColor, isHighlighted, fastMode) {
        ctx.save();
        const midY = (p1.y + p2.y) / 2;
        const cp1 = { x: p1.x, y: midY };
        const cp2 = { x: p2.x, y: midY };

        ctx.shadowColor = glowColor;
        ctx.shadowBlur = fastMode ? 0 : (isHighlighted ? 20 : 8);

        ctx.beginPath();
        ctx.moveTo(p1.x, p1.y);
        ctx.bezierCurveTo(cp1.x, cp1.y, cp2.x, cp2.y, p2.x, p2.y);
        ctx.strokeStyle = color;
        ctx.lineWidth = (startWidth + endWidth) / 2;
        ctx.lineCap = "round";
        ctx.stroke();

        ctx.restore();
    }

    function drawUSBTridentBranch(p1, p2, color, glowColor, isHighlighted, node, fastMode) {
        ctx.save();
        ctx.shadowColor = glowColor;
        ctx.shadowBlur = fastMode ? 0 : (isHighlighted ? 18 : 8);
        ctx.strokeStyle = color;
        ctx.lineWidth = isHighlighted ? 3.5 : 2;
        ctx.lineCap = "square";

        ctx.beginPath();

        if (node && node.branchOriginY !== undefined) {
            const startX = p1.x;
            const startY = node.branchOriginY;

            ctx.moveTo(startX, startY);

            const dx = p2.x - startX;
            const bendDist = Math.abs(dx) * 0.5;
            const bendY = startY - bendDist;

            ctx.lineTo(startX + dx * 0.5, bendY);
            ctx.lineTo(p2.x, bendY);
            ctx.lineTo(p2.x, p2.y);
        } else {
            const dx = p2.x - p1.x;
            const dy = p2.y - p1.y;

            ctx.moveTo(p1.x, p1.y);

            if (Math.abs(dx) < 10) {
                ctx.lineTo(p2.x, p2.y);
            } else {
                const bendDist = Math.min(Math.abs(dx), Math.abs(dy) * 0.5);
                const cornerY = p1.y - bendDist;
                
                ctx.lineTo(p1.x, p1.y - 20);
                ctx.lineTo(p2.x, cornerY);
                ctx.lineTo(p2.x, p2.y);
            }
        }

        ctx.stroke();
        ctx.restore();
    }

    function drawTrunkAndRoots(cx, cy, isCoreActive, trunkTopY, fastMode) {
        ctx.save();
        const baseWidth = width * 0.85;       
        const kneeWidth = width * 0.18;       
        const topWidth = 95;                  

        ctx.beginPath();
        ctx.moveTo(cx - baseWidth / 2, cy);
        ctx.lineTo(cx - kneeWidth, cy - height * 0.08);
        ctx.bezierCurveTo(
            cx - kneeWidth * 0.45, cy - height * 0.30, 
            cx - topWidth * 0.85, trunkTopY + height * 0.05, 
            cx - topWidth / 2, trunkTopY 
        );
        ctx.lineTo(cx + topWidth / 2, trunkTopY);
        ctx.bezierCurveTo(
            cx + topWidth * 0.85, trunkTopY + height * 0.05,
            cx + kneeWidth * 0.45, cy - height * 0.30,
            cx + kneeWidth, cy - height * 0.08
        );
        ctx.lineTo(cx + baseWidth / 2, cy);
        ctx.closePath();

        const trunkGrad = ctx.createLinearGradient(cx, trunkTopY, cx, cy);
        trunkGrad.addColorStop(0, "#003b60");
        trunkGrad.addColorStop(0.35, "#001e36");
        trunkGrad.addColorStop(1, "#000a14");

        ctx.fillStyle = trunkGrad;
        ctx.shadowColor = "#00f0ff";
        ctx.shadowBlur = fastMode ? 0 : (isCoreActive ? 25 : 12);
        ctx.strokeStyle = "#00f0ff";
        ctx.lineWidth = 2.5;
        ctx.fill();
        ctx.stroke();

        ctx.beginPath();
        ctx.moveTo(cx, cy - 110);
        ctx.lineTo(cx, trunkTopY);
        ctx.strokeStyle = "#00f0ff";
        ctx.lineWidth = 12;
        ctx.shadowColor = "#00f0ff";
        ctx.shadowBlur = fastMode ? 0 : 15;
        ctx.lineCap = "round";
        ctx.stroke();

        ctx.restore();
    }

    function draw() {
        ctx.clearRect(0, 0, width, height);

        const isTransitioning = Math.abs(camera.targetX - camera.x) > 0.5 || 
                                Math.abs(camera.targetY - camera.y) > 0.5 || 
                                Math.abs(camera.targetZoom - camera.zoom) > 0.005;

        camera.x += (camera.targetX - camera.x) * 0.08;
        camera.y += (camera.targetY - camera.y) * 0.08;
        camera.zoom += (camera.targetZoom - camera.zoom) * 0.08;

        ctx.save();
        ctx.translate(width / 2, height / 2);
        ctx.scale(camera.zoom, camera.zoom);
        ctx.translate(-width / 2 - camera.x, -height / 2 - camera.y);

        const nodes = getNodes();
        const cx = width / 2;
        const cy = height;
        const trunkTopY = cy - height * 0.65;

        const apexNode = { id: "apex", label: "APEX", type: "virtual", x: cx, y: trunkTopY, radius: 0 };
        const nodesMap = { "apex": apexNode };
        nodes.forEach(n => nodesMap[n.id] = n);

        const coreNode = nodesMap["core"];

        // 1. NEON ARKA PLAN DALLARI
        if (!selectedMainCategory && !isTransitioning) {
            ctx.save();
            backgroundBranches.forEach(b => {
                ctx.beginPath();
                ctx.moveTo(b.x1, b.y1);
                ctx.quadraticCurveTo(b.cpX, b.cpY, b.x2, b.y2);
                ctx.strokeStyle = `rgba(0, 240, 255, ${b.alpha})`;
                ctx.lineWidth = b.width;
                ctx.stroke();
            });
            ctx.restore();
        }

        // 2. POLENLER
        if (!isTransitioning) {
            ctx.save();
            particles.forEach(p => {
                p.x += p.vx;
                p.y += p.vy;
                if (p.y < 0) p.y = height;
                if (p.x < 0) p.x = width;
                if (p.x > width) p.x = 0;

                ctx.beginPath();
                ctx.arc(p.x, p.y, p.size, 0, Math.PI * 2);
                ctx.fillStyle = `rgba(0, 240, 255, ${p.alpha})`;
                ctx.fill();
            });
            ctx.restore();
        }

        // 3. MASİF KÜTÜK
        const isCoreHovered = hoveredNode && hoveredNode.id === "core";
        drawTrunkAndRoots(coreNode.x, height, isCoreHovered, trunkTopY, isTransitioning);

        // 4. BAĞLANTI HATLARI
        nodes.forEach(node => {
            if (node.parent) {
                const parentNode = nodesMap[node.parent];
                if (!parentNode) return;

                const isHighlighted = (hoveredNode && (hoveredNode.id === node.id || hoveredNode.id === node.parent)) ||
                                      (activeNode && (activeNode.id === node.id || activeNode.id === node.parent));

                const branchColor = node.isCorrupted ? "#ff0055" : (isHighlighted ? "#ffffff" : "#00f0ff");
                const glowColor = node.isCorrupted ? "#ff0055" : "#00f0ff";

                if (node.type === "usb_node") {
                    drawUSBTridentBranch(
                        { x: parentNode.x, y: parentNode.y },
                        { x: node.x, y: node.y },
                        branchColor, glowColor, isHighlighted, node, isTransitioning
                    );
                } else {
                    let startW = node.parent === "apex" ? 12 : 18;
                    let endW = 6;
                    drawTaperedBranch(
                        { x: parentNode.x, y: parentNode.y },
                        { x: node.x, y: node.y },
                        startW, endW,
                        branchColor, glowColor, isHighlighted, isTransitioning
                    );
                }
            }
        });

        // 5. DÜĞÜMLER
        nodes.forEach(node => {
            const isHovered = hoveredNode && hoveredNode.id === node.id;
            const isActive = activeNode && activeNode.id === node.id;

            ctx.save();

            if (node.type === "usb_node") {
                ctx.fillStyle = node.isCorrupted ? "#330011" : (isHovered ? "#004466" : "#001224");
                ctx.strokeStyle = node.isCorrupted ? "#ff0055" : (isHovered ? "#ffffff" : "#00f0ff");
                ctx.lineWidth = 2;
                ctx.shadowColor = node.color;
                ctx.shadowBlur = isTransitioning ? 0 : (isHovered ? 15 : 6);

                if (node.shape === "arrow") {
                    const size = node.radius + (isHovered ? 4 : 0);
                    ctx.beginPath();
                    ctx.moveTo(node.x, node.y - size - 4);
                    ctx.lineTo(node.x - size, node.y + size);
                    ctx.lineTo(node.x + size, node.y + size);
                    ctx.closePath();
                    ctx.fill();
                    ctx.stroke();
                } else if (node.shape === "square") {
                    const size = (node.radius + (isHovered ? 2 : 0)) * 1.4;
                    ctx.fillRect(node.x - size / 2, node.y - size / 2, size, size);
                    ctx.strokeRect(node.x - size / 2, node.y - size / 2, size, size);
                } else {
                    ctx.beginPath();
                    ctx.arc(node.x, node.y, isHovered ? node.radius + 3 : node.radius, 0, Math.PI * 2);
                    ctx.fill();
                    ctx.stroke();
                }
            } else {
                if (node.type === "root" || isHovered || isActive) {
                    ctx.beginPath();
                    ctx.arc(node.x, node.y, node.radius + (isHovered ? 10 : 6), 0, Math.PI * 2);
                    ctx.strokeStyle = node.isCorrupted ? "rgba(255, 0, 85, 0.6)" : "rgba(0, 240, 255, 0.6)";
                    ctx.lineWidth = 1.5;
                    ctx.stroke();
                }

                ctx.beginPath();
                ctx.arc(node.x, node.y, isHovered ? node.radius + 3 : node.radius, 0, Math.PI * 2);
                ctx.fillStyle = node.isCorrupted ? "#330011" : (isHovered ? "#003355" : "#001224");
                ctx.strokeStyle = node.isCorrupted ? "#ff0055" : "#00f0ff";
                ctx.lineWidth = node.type === "root" ? 3 : 2;
                ctx.shadowColor = node.color;
                ctx.shadowBlur = isTransitioning ? 0 : (isHovered ? 20 : 8);
                ctx.fill();
                ctx.stroke();

                ctx.beginPath();
                ctx.arc(node.x, node.y, node.radius * 0.4, 0, Math.PI * 2);
                ctx.fillStyle = node.isCorrupted ? "#ff0055" : (isHovered ? "#ffffff" : "#00f0ff");
                ctx.fill();
            }

            // Etiket
            ctx.font = node.type === "root" ? "bold 13px Courier New" : "bold 11px Courier New";
            ctx.textAlign = "center";
            ctx.textBaseline = "middle";

            const text = node.label;
            const textWidth = ctx.measureText(text).width;
            const paddingX = 6;
            const paddingY = 3;
            const boxWidth = textWidth + paddingX * 2;
            const boxHeight = (node.type === "root" ? 13 : 11) + paddingY * 2;

            const labelY = node.y - node.radius - (node.type === "root" ? 18 : 14);
            const boxX = node.x - boxWidth / 2;
            const boxY = labelY - boxHeight / 2;

            ctx.fillStyle = "rgba(2, 9, 20, 0.85)";
            ctx.fillRect(boxX, boxY, boxWidth, boxHeight);

            ctx.strokeStyle = node.isCorrupted ? "rgba(255, 0, 85, 0.7)" : "rgba(0, 240, 255, 0.4)";
            ctx.lineWidth = 1;
            ctx.strokeRect(boxX, boxY, boxWidth, boxHeight);

            ctx.fillStyle = node.isCorrupted ? "#ff0055" : (isHovered ? "#ffffff" : "#00f0ff");
            ctx.fillText(text, node.x, labelY);

            ctx.restore();
        });

        ctx.restore();
        requestAnimationFrame(draw);
    }

    // --- ETKİLEŞİM MANTIGI ---
    canvas.addEventListener("mousemove", (e) => {
        const rect = canvas.getBoundingClientRect();
        const rawMx = e.clientX - rect.left;
        const rawMy = e.clientY - rect.top;

        const mx = (rawMx - width / 2) / camera.zoom + width / 2 + camera.x;
        const my = (rawMy - height / 2) / camera.zoom + height / 2 + camera.y;

        const nodes = getNodes();
        let found = null;

        nodes.forEach(node => {
            const dist = Math.hypot(mx - node.x, my - node.y);
            if (dist < node.radius + 15) {
                found = node;
            }
        });

        hoveredNode = found;
        canvas.style.cursor = found ? "pointer" : "default";
    });

    canvas.addEventListener("click", () => {
        if (!hoveredNode) {
            resetCamera();
            return;
        }

        activeNode = hoveredNode;
        const isMobile = width < 768;

        if (["past", "present", "future"].includes(hoveredNode.id)) {
            selectedMainCategory = hoveredNode.id;
            camera.targetX = hoveredNode.x - width / 2;
            camera.targetY = (hoveredNode.y - (isMobile ? 380 : 490)) - height / 2;
            camera.targetZoom = isMobile ? 0.85 : 1.3;
        } else {
            camera.targetX = hoveredNode.x - width / 2;
            camera.targetY = hoveredNode.y - height / 2;
            camera.targetZoom = isMobile ? 0.95 : 1.4;
        }

        panel.classList.remove("hidden");

        if (hoveredNode.isCorrupted) {
            panel.classList.add("corrupted");
            panelBadge.textContent = "CRITICAL PARADOX";
            riskVal.textContent = "99.8% (TIMELINE COLLAPSE)";
        } else {
            panel.classList.remove("corrupted");
            panelBadge.textContent = "STABLE DATA";
            riskVal.textContent = "2.1% (OPTIMAL)";
        }

        panelTitle.textContent = hoveredNode.label;
        typeWriterEffect(panelContent, hoveredNode.desc, 15);
    });

    closeBtn.addEventListener("click", () => {
        panel.classList.add("hidden");
        activeNode = null;
        if (activeTypewriterTimer) {
            clearTimeout(activeTypewriterTimer);
            activeTypewriterTimer = null;
        }
        panelContent.textContent = "";
    });

    function resetCamera() {
        activeNode = null;
        selectedMainCategory = null; 
        panel.classList.add("hidden");

        const isMobile = width < 768;
        const isPortrait = height > width;

        camera.targetX = 0;
        camera.targetY = (isMobile && isPortrait) ? -height * 0.35 : 0;
        camera.targetZoom = (isMobile && isPortrait) ? 0.45 : 1;

        if (activeTypewriterTimer) {
            clearTimeout(activeTypewriterTimer);
            activeTypewriterTimer = null;
        }
        panelContent.textContent = "";
    }

    resetZoomBtn.addEventListener("click", resetCamera);

    draw();
});
